 CREATE TABLE "SYS"."DIM_RAW_MAT" 
   (	"MATERIAL_ID" NUMBER(38,0), 
	"MATERIAL" VARCHAR2(26 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE DIM_RAW_MAT
ADD CONSTRAINT DIM_RAW_MAT_pk PRIMARY KEY (MATERIAL_ID);