
  CREATE TABLE "SYS"."DIM_STATE" 
   (	"STATE_N" VARCHAR2(26 BYTE), 
	"GDP" NUMBER(38,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE dim_state
ADD CONSTRAINT dim_state_pk PRIMARY KEY (STATE_N);