
  CREATE TABLE "SYS"."DIM_RAW_PRICE" 
   (	"PRICE_RAW" NUMBER(38,0), 
	"MATERIAL_ID" NUMBER(38,0), 
	"DATE_P" DATE, 
	"PRICE" NUMBER(38,1), 
	"HIGH" NUMBER(38,1), 
	"LOW" NUMBER(38,1), 
	"CHANGE" NUMBER(38,9)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE DIM_RAW_PRICE
ADD CONSTRAINT DIM_RAW_PRICE_PK PRIMARY KEY (PRICE_RAW);

ALTER TABLE DIM_RAW_PRICE
ADD CONSTRAINT DIM_RAW_PRICE_FK FOREIGN KEY (MATERIAL_ID) REFERENCES DIM_RAW_MAT(MATERIAL_ID);