
  CREATE TABLE "SYS"."DIM_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(38,0), 
	"NAME" VARCHAR2(128 BYTE), 
	"CUSTOMER_AGE" NUMBER(38,0), 
	"GENDER" VARCHAR2(26 BYTE), 
	"EDUCATION_LEVEL" VARCHAR2(26 BYTE), 
	"MARITAL_STATUS" VARCHAR2(26 BYTE), 
	"INCOME_CATEGORY" VARCHAR2(26 BYTE), 
	"STATE" VARCHAR2(26 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE DIM_CUSTOMERS
ADD CONSTRAINT DIM_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID);