
  CREATE TABLE "SYS"."DIM_TIME" 
   (	"DATE_TRANS" DATE, 
	"DAY_OF_WEEK" VARCHAR2(26 BYTE), 
	"MONTH" NUMBER(38,0), 
	"MONTH_ALPHA" VARCHAR2(26 BYTE), 
	"YEAR" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE DIM_TIME
ADD CONSTRAINT DIM_TIME_PK PRIMARY KEY (DATE_TRANS);