
  CREATE TABLE "SYS"."DIM_PRODUCTS" 
   (	"PRODUCT_ID_" VARCHAR2(26 BYTE), 
	"CATEGORY" VARCHAR2(26 BYTE), 
	"TITLE" VARCHAR2(128 BYTE), 
	"QUANTITY" NUMBER(38,0), 
	"PRICE_RAW" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE DIM_PRODUCTS
ADD CONSTRAINT DIM_PRODUCTS_PK PRIMARY KEY (PRODUCT_ID_);

ALTER TABLE DIM_PRODUCTS
ADD CONSTRAINT DIM_PRODUCTS_FK FOREIGN KEY (PRICE_RAW) REFERENCES DIM_RAW_PRICE(PRICE_RAW);