
  CREATE TABLE "SYS"."DIM_STORES" 
   (	"STORE_ID" NUMBER(38,0), 
	"STATE" VARCHAR2(26 BYTE), 
	"NB_EMPLOYEES" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE DIM_STORES
ADD CONSTRAINT DIM_STORES_PK PRIMARY KEY (STORE_ID);

ALTER TABLE DIM_STORES
ADD CONSTRAINT DIM_STORES_FK FOREIGN KEY (STATE) REFERENCES dim_state(STATE);