
  CREATE TABLE "SYS"."FACT_SALES" 
   (	"PRODUCT_ID" VARCHAR2(26 BYTE), 
	"STORE_ID" NUMBER(38,0), 
	"CUSTOMER_ID" NUMBER(38,0), 
	"DATE_TRANS" DATE, 
	"TYPE" VARCHAR2(26 BYTE), 
	"PRICE" NUMBER(38,0), 
	"COST" NUMBER(38,0), 
	"PROFIT" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE FACT_SALES
ADD CONSTRAINT FACT_SALES_FK FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCTS(PRODUCT_ID_);

ALTER TABLE FACT_SALES
ADD CONSTRAINT FACT_SALES_FK2 FOREIGN KEY (STORE_ID) REFERENCES DIM_STORES(STORE_ID);

ALTER TABLE FACT_SALES
ADD CONSTRAINT FACT_SALES_FK3 FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMERS(CUSTOMER_ID);

ALTER TABLE FACT_SALES
ADD CONSTRAINT FACT_SALES_FK4 FOREIGN KEY (DATE_TRANS) REFERENCES DIM_TIME(DATE_TRANS);


